server:
  port: 8080
spring:
  profiles:
    active: query_route


---
#The After Route Predicate Factory
spring:
  cloud:
    gateway:
      routes:
        - id: after_route
          uri: http://httpbin.org:80/get
          predicates:
            - After=2022-05-20T10:40:14.334+08:00[Asia/Shanghai]
  profiles: after_route


---
#The Header Route Predicate Factory
#curl -H "X-Request-Id:1" localhost:8080
spring:
  cloud:
    gateway:
      routes:
        - id: header_route
          uri: http://httpbin.org:80/get
          predicates:
            - Header=X-Request-Id, \d+
  profiles: header_route


---
#The Cookie Route Predicate Factory
#curl -H "Cookie:keyName=Yu" localhost:8080
spring:
  cloud:
    gateway:
      routes:
        - id: cookie_route
          uri: http://httpbin.org:80/get
          predicates:
            - Cookie=keyName, Yu
  profiles: cookie_route


---
#The Host Route Predicate Factory
#curl -H "Host:www.yu.com" localhost:8080
spring:
  cloud:
    gateway:
      routes:
        - id: host_route
          uri: http://httpbin.org:80/get
          predicates:
            - Host=**.yu.com
  profiles: host_route


---
#The Method Route Predicate Factory
#curl localhost:8080   curl -XPOST localhost:8080
spring:
  cloud:
    gateway:
      routes:
        - id: method_route
          uri: http://httpbin.org:80/get
          predicates:
            - Method=GET
  profiles: method_route


---
#The Path Route Predicate Factory
#curl localhost:8080/path/hello
spring:
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: http://httpbin.org:80/get
          predicates:
            - Path=/path/{segment}
  profiles: path_route


---
#The Query Route Predicate Factory
#curl localhost:8080?key=value
spring:
  cloud:
    gateway:
      routes:
        - id: query_route
          uri: http://httpbin.org:80/get
          predicates:
            - Query=key, value
          # - Query=key
  profiles: query_route