server:
  port: 8762

spring:
  application:
    name: service-provider

  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defalutZone: http://localhost:8761/eureka/