server:
  port: 8763

spring:
  application:
    name: service-consumer

  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defalutZone: http://localhost:8761/eureka/
management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: hystrix.stream