server:
  port: 8761

eureka:
  instance:
    hostname: peer1
  client:
    # 是否注册到 eureka
    register-with-eureka: false
    # 是否从eureka获取注册信息
    fetch-registry: false
    service-url:
      defaultZone: http://peer2:8768/eureka/,http://peer3:8769/eureka/

spring:
  application:
    name: eureka-server-peer1